### ISSUE TITLE
v0.1.1 not available

### ISSUE THREAD

**Issue by lukechampine** [famousj/hoon-vscode#3]
The latest release available in the Visual Studio Marketplace is v0.1.0, which doesn't have language server support. Can you push v0.1.1?

**Comment by Fang-** [comment]
Ping on this. Please, and thank you. (:

**Comment by prios-justin-leblanc** [comment]
Thank you for the reminder.  I'm on it (finally)!

**Comment by famousj** [comment]
https://marketplace.visualstudio.com/items?itemName=urbit.hoon

Updated!  @Fang- would you mind updating and making sure this works on your box?

**Comment by Fang-** [comment]
idk about the language server, but latest version does have proper commenting support included. (:

**Comment by famousj** [comment]
Closing this, since we are now pushed to the marketplace.  Will investigate the other issue...
